// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.item;

import com.amazon.webservices.awsecommerceservice._2011_08_01.item.alternateversions.AlternateVersion;

import java.io.Serializable;
import java.util.List;

public class AlternateVersions implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "AlternateVersion")
    @Order(value = 0)
    public List<AlternateVersion> alternateVersion;


}