// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.item;

import com.amazon.webservices.awsecommerceservice._2011_08_01.ImageSet;

import java.io.Serializable;
import java.util.List;

public class ImageSets implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "ImageSet")
    @Order(value = 0)
    public List<ImageSet> imageSet;


}