// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.searchresultsmap;

import com.amazon.webservices.awsecommerceservice._2011_08_01.CorrectedQuery;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;

public class SearchIndex implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "IndexName")
    @Order(value = 0)
    public String indexName;

    @Element(name = "Results")
    @Order(value = 1)
    public BigInteger results;

    @Element(name = "Pages")
    @Order(value = 2)
    public BigInteger pages;

    @Element(name = "CorrectedQuery")
    @Order(value = 3)
    public CorrectedQuery correctedQuery;

    @Element(name = "RelevanceRank")
    @Order(value = 4)
    public BigInteger relevanceRank;

    @Element(name = "ASIN")
    @Order(value = 5)
    public List<String> asin;


}