// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package com.ebay.shopping.api.client;


import com.ebay.shopping.api.*;
import com.leansoft.nano.ws.NanoSOAPClient;
import com.leansoft.nano.ws.SOAPServiceCallback;


/**
 * This class is the SOAP client to the ShoppingInterface Web Service.
 */
public class ShoppingInterface_SOAPClient extends NanoSOAPClient {


    /**
     * public method
     */
    public void findHalfProducts(FindHalfProductsRequestType requestObject, SOAPServiceCallback<FindHalfProductsResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindHalfProductsResponseType.class);
    }

    /**
     * public method
     */
    public void findPopularItems(FindPopularItemsRequestType requestObject, SOAPServiceCallback<FindPopularItemsResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindPopularItemsResponseType.class);
    }

    /**
     * public method
     */
    public void findPopularSearches(FindPopularSearchesRequestType requestObject, SOAPServiceCallback<FindPopularSearchesResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindPopularSearchesResponseType.class);
    }

    /**
     * public method
     */
    public void findProducts(FindProductsRequestType requestObject, SOAPServiceCallback<FindProductsResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindProductsResponseType.class);
    }

    /**
     * public method
     */
    public void findReviewsAndGuides(FindReviewsAndGuidesRequestType requestObject, SOAPServiceCallback<FindReviewsAndGuidesResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindReviewsAndGuidesResponseType.class);
    }

    /**
     * public method
     */
    public void getCategoryInfo(GetCategoryInfoRequestType requestObject, SOAPServiceCallback<GetCategoryInfoResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GetCategoryInfoResponseType.class);
    }

    /**
     * public method
     */
    public void getItemStatus(GetItemStatusRequestType requestObject, SOAPServiceCallback<GetItemStatusResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GetItemStatusResponseType.class);
    }

    /**
     * public method
     */
    public void getMultipleItems(GetMultipleItemsRequestType requestObject, SOAPServiceCallback<GetMultipleItemsResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GetMultipleItemsResponseType.class);
    }

    /**
     * public method
     */
    public void getShippingCosts(GetShippingCostsRequestType requestObject, SOAPServiceCallback<GetShippingCostsResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GetShippingCostsResponseType.class);
    }

    /**
     * public method
     */
    public void getSingleItem(GetSingleItemRequestType requestObject, SOAPServiceCallback<GetSingleItemResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GetSingleItemResponseType.class);
    }

    /**
     * public method
     */
    public void getUserProfile(GetUserProfileRequestType requestObject, SOAPServiceCallback<GetUserProfileResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GetUserProfileResponseType.class);
    }

    /**
     * public method
     */
    public void geteBayTime(GeteBayTimeRequestType requestObject, SOAPServiceCallback<GeteBayTimeResponseType> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GeteBayTimeResponseType.class);
    }


}