// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.browsenode;

import com.amazon.webservices.awsecommerceservice._2011_08_01.Property;

import java.io.Serializable;
import java.util.List;

public class Properties implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "Property")
    @Order(value = 0)
    public List<Property> property;


}