// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package com.webservicemart.ws.client;


import com.leansoft.nano.ws.NanoSOAPClient;
import com.leansoft.nano.ws.SOAPServiceCallback;
import com.webservicemart.ws.ValidateZip;
import com.webservicemart.ws.ValidateZipResponse;


/**
 * This class is the SOAP client to the USZipSoap Web Service.
 */
public class USZipSoap_SOAPClient extends NanoSOAPClient {


    /**
     * Returns United States Postal Service State Abbreviation, Latitude (decimal degrees) and Longitude (decimal degrees).
     */
    public void validateZip(ValidateZip requestObject, SOAPServiceCallback<ValidateZipResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, ValidateZipResponse.class);
    }


}