// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.cartitem;

import com.amazon.webservices.awsecommerceservice._2011_08_01.cartitem.metadata.KeyValuePair;

import java.io.Serializable;
import java.util.List;

public class MetaData implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "KeyValuePair")
    @Order(value = 0)
    public List<KeyValuePair> keyValuePair;


}