// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.collections;

import com.amazon.webservices.awsecommerceservice._2011_08_01.collections.collection.CollectionItem;
import com.amazon.webservices.awsecommerceservice._2011_08_01.collections.collection.CollectionParent;
import com.amazon.webservices.awsecommerceservice._2011_08_01.collections.collection.CollectionSummary;

import java.io.Serializable;
import java.util.List;

public class Collection implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "CollectionSummary")
    @Order(value = 0)
    public CollectionSummary collectionSummary;

    @Element(name = "CollectionParent")
    @Order(value = 1)
    public CollectionParent collectionParent;

    @Element(name = "CollectionItem")
    @Order(value = 2)
    public List<CollectionItem> collectionItem;


}