// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;

/**
 * Response to DisableUnpaidItemAssistance request.
 */
@RootElement(name = "DisableUnpaidItemAssistanceResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class DisableUnpaidItemAssistanceResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;


}