// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Contains all information about a dispute resolution. A dispute
 * can have a resolution even if the seller does not receive payment.
 * The resolution can have various results, including a Final Value Fee credit to
 * the seller or a strike to the buyer.
 */
public class DisputeResolutionType implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "DisputeResolutionRecordType")
    @Order(value = 0)
    public DisputeResolutionRecordTypeCodeType disputeResolutionRecordType;

    @Element(name = "DisputeResolutionReason")
    @Order(value = 1)
    public DisputeResolutionReasonCodeType disputeResolutionReason;

    @Element(name = "ResolutionTime")
    @Order(value = 2)
    public Date resolutionTime;

    @AnyElement
    @Order(value = 3)
    public List<Object> any;


}