// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;

/**
 * Sets the configuration of the eBay store owned by the caller.
 */
@RootElement(name = "SetStoreRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SetStoreRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "Store")
    @Order(value = 0)
    public StoreType store;


}