// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;

/**
 * Store Preferences type.
 */
public class StorePreferencesType implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "VacationPreferences")
    @Order(value = 0)
    public StoreVacationPreferencesType vacationPreferences;


}