// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.client;


import com.amazon.webservices.awsecommerceservice._2011_08_01.*;
import com.leansoft.nano.ws.NanoSOAPClient;
import com.leansoft.nano.ws.SOAPServiceCallback;


/**
 * This class is the SOAP client to the AWSECommerceServicePortType Web Service.
 */
public class AWSECommerceServicePortType_SOAPClient extends NanoSOAPClient {


    /**
     * public method
     */
    public void itemSearch(ItemSearch requestObject, SOAPServiceCallback<ItemSearchResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, ItemSearchResponse.class);
    }

    /**
     * public method
     */
    public void itemLookup(ItemLookup requestObject, SOAPServiceCallback<ItemLookupResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, ItemLookupResponse.class);
    }

    /**
     * public method
     */
    public void browseNodeLookup(BrowseNodeLookup requestObject, SOAPServiceCallback<BrowseNodeLookupResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, BrowseNodeLookupResponse.class);
    }

    /**
     * public method
     */
    public void similarityLookup(SimilarityLookup requestObject, SOAPServiceCallback<SimilarityLookupResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, SimilarityLookupResponse.class);
    }

    /**
     * public method
     */
    public void cartGet(CartGet requestObject, SOAPServiceCallback<CartGetResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, CartGetResponse.class);
    }

    /**
     * public method
     */
    public void cartCreate(CartCreate requestObject, SOAPServiceCallback<CartCreateResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, CartCreateResponse.class);
    }

    /**
     * public method
     */
    public void cartAdd(CartAdd requestObject, SOAPServiceCallback<CartAddResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, CartAddResponse.class);
    }

    /**
     * public method
     */
    public void cartModify(CartModify requestObject, SOAPServiceCallback<CartModifyResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, CartModifyResponse.class);
    }

    /**
     * public method
     */
    public void cartClear(CartClear requestObject, SOAPServiceCallback<CartClearResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, CartClearResponse.class);
    }


}