// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import java.util.List;

/**
 * Not applicable to any site. Formerly applicable to the
 * Australia site (site ID 15, abbreviation AU) only.
 */
public class BasicUpgradePackEnabledDefinitionType implements Serializable {

    private static final long serialVersionUID = -1L;

    @AnyElement
    @Order(value = 0)
    public List<Object> any;


}