// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;

public class FeedbackRequirementsType implements Serializable {

    private static final long serialVersionUID = -1L;

    @Value
    @Order(value = 0)
    public boolean value;

    @Attribute
    @Order(value = 1)
    public String minimum;


}