// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@RootElement(name = "GetCategoryFeaturesResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetCategoryFeaturesResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "CategoryVersion")
    @Order(value = 0)
    public String categoryVersion;

    @Element(name = "UpdateTime")
    @Order(value = 1)
    public Date updateTime;

    @Element(name = "Category")
    @Order(value = 2)
    public List<CategoryFeatureType> category;

    @Element(name = "SiteDefaults")
    @Order(value = 3)
    public SiteDefaultsType siteDefaults;

    @Element(name = "FeatureDefinitions")
    @Order(value = 4)
    public FeatureDefinitionsType featureDefinitions;


}