// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;

/**
 * Returns the status of move folder operation.
 */
@RootElement(name = "MoveSellingManagerInventoryFolderResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class MoveSellingManagerInventoryFolderResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;


}