// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;

/**
 * Returns the status of calling SendInvoice.
 */
@RootElement(name = "SendInvoiceResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SendInvoiceResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;


}