// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;

/**
 * Returns the success or failure of the
 * SetMessagePreferencesRequest, and any applicable errors.
 */
@RootElement(name = "SetMessagePreferencesResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SetMessagePreferencesResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;


}