// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.nano.soap11;

import com.leansoft.nano.annotation.AnyElement;
import com.leansoft.nano.annotation.Order;
import com.leansoft.nano.annotation.RootElement;

import java.io.Serializable;
import java.util.List;

@RootElement(name = "Header", namespace = "http://schemas.xmlsoap.org/soap/envelope/")
public class Header implements Serializable {

    private static final long serialVersionUID = -1L;

    @AnyElement
    @Order(value = 0)
    public List<Object> any;


}