// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package com.dataaccess.webservicesserver.client;


import com.dataaccess.webservicesserver.NumberToDollars;
import com.dataaccess.webservicesserver.NumberToDollarsResponse;
import com.dataaccess.webservicesserver.NumberToWords;
import com.dataaccess.webservicesserver.NumberToWordsResponse;
import com.leansoft.nano.ws.NanoXMLClient;
import com.leansoft.nano.ws.XMLServiceCallback;


/**
 * This class is the XML client to the NumberConversionSoapType Web Service.
 */
public class NumberConversionSoapType_XMLClient extends NanoXMLClient {


    /**
     * Returns the word corresponding to the positive number passed as parameter. Limited to quadrillions.
     */
    public void numberToWords(NumberToWords requestObject, XMLServiceCallback<NumberToWordsResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, NumberToWordsResponse.class);
    }

    /**
     * Returns the non-zero dollar amount of the passed number.
     */
    public void numberToDollars(NumberToDollars requestObject, XMLServiceCallback<NumberToDollarsResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, NumberToDollarsResponse.class);
    }


}