// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.nano.soap12;

import com.leansoft.nano.annotation.Element;
import com.leansoft.nano.annotation.Order;

import javax.xml.namespace.QName;
import java.io.Serializable;

public class Subcode implements Serializable {

    private static final long serialVersionUID = -1L;

    @Element(name = "Value")
    @Order(value = 0)
    public QName value;

    @Element(name = "Subcode")
    @Order(value = 1)
    public Subcode subcode;


}