// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.nano.soap12;

import com.leansoft.nano.annotation.Attribute;
import com.leansoft.nano.annotation.Order;

import javax.xml.namespace.QName;
import java.io.Serializable;

public class SupportedEnvType implements Serializable {

    private static final long serialVersionUID = -1L;

    @Attribute
    @Order(value = 0)
    public QName qname;


}