// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package com.ebay.finding.api.client;


import com.ebay.finding.api.*;
import com.leansoft.nano.ws.NanoXMLClient;
import com.leansoft.nano.ws.XMLServiceCallback;


/**
 * This class is the XML client to the FindingServicePortType Web Service.
 */
public class FindingServicePortType_XMLClient extends NanoXMLClient {


    /**
     * public method
     */
    public void getSearchKeywordsRecommendation(GetSearchKeywordsRecommendationRequest requestObject, XMLServiceCallback<GetSearchKeywordsRecommendationResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GetSearchKeywordsRecommendationResponse.class);
    }

    /**
     * public method
     */
    public void findItemsByKeywords(FindItemsByKeywordsRequest requestObject, XMLServiceCallback<FindItemsByKeywordsResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindItemsByKeywordsResponse.class);
    }

    /**
     * public method
     */
    public void findItemsByCategory(FindItemsByCategoryRequest requestObject, XMLServiceCallback<FindItemsByCategoryResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindItemsByCategoryResponse.class);
    }

    /**
     * public method
     */
    public void findItemsAdvanced(FindItemsAdvancedRequest requestObject, XMLServiceCallback<FindItemsAdvancedResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindItemsAdvancedResponse.class);
    }

    /**
     * public method
     */
    public void findItemsByProduct(FindItemsByProductRequest requestObject, XMLServiceCallback<FindItemsByProductResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindItemsByProductResponse.class);
    }

    /**
     * public method
     */
    public void findItemsIneBayStores(FindItemsIneBayStoresRequest requestObject, XMLServiceCallback<FindItemsIneBayStoresResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindItemsIneBayStoresResponse.class);
    }

    /**
     * public method
     */
    public void findItemsByImage(FindItemsByImageRequest requestObject, XMLServiceCallback<FindItemsByImageResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindItemsByImageResponse.class);
    }

    /**
     * public method
     */
    public void getHistograms(GetHistogramsRequest requestObject, XMLServiceCallback<GetHistogramsResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GetHistogramsResponse.class);
    }

    /**
     * public method
     */
    public void findCompletedItems(FindCompletedItemsRequest requestObject, XMLServiceCallback<FindCompletedItemsResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindCompletedItemsResponse.class);
    }

    /**
     * public method
     */
    public void getVersion(GetVersionRequest requestObject, XMLServiceCallback<GetVersionResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, GetVersionResponse.class);
    }

    /**
     * public method
     */
    public void findItemsForFavoriteSearch(FindItemsForFavoriteSearchRequest requestObject, XMLServiceCallback<FindItemsForFavoriteSearchResponse> serviceCallback) {


        super.invoke(requestObject, serviceCallback, FindItemsForFavoriteSearchResponse.class);
    }


}